server {
    server_name kutipcrew.nusabyte.cloud;

    root /opt/kutipcrew/web/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/kutipcrew.nusabyte.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kutipcrew.nusabyte.cloud/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = kutipcrew.nusabyte.cloud) { return 301 https://$host$request_uri; }
    listen 80;
    server_name kutipcrew.nusabyte.cloud;
    return 404;
}